### ISSUE TITLE
The Octez documentation shouldn't be referenced as "the Nomadic Labs documentation"

### ISSUE THREAD

**Issue by germanD** [trilitech/tezos-developer-docs#100]
In places like 

https://docs.tezos.com/tezos-basics/tezos-protocol-and-shell/

![Screenshot from 2023-09-04 16-55-26](https://github.com/trilitech/tezos-developer-docs/assets/4624212/4d96807c-d9da-4b2d-a702-a75800e59924)

this siter efers to the Octez/ Tezos technical documentation as "the Nomadic Labs documentation". This is incorrect, as it is the technical Documentation of the whole project.

**Comment by sashaaldrick** [comment]
This has been fixed in PR #104, but please for future reference, open your own PR to fix small changes like this, and I would be glad to approve them.
