### ISSUE TITLE
[New Page Request]

### ISSUE THREAD

**Issue by Georgezhang714** [trilitech/tezos-developer-docs#121]
**Is your documentation request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always struggling to understand [...]

**Describe the new documentation page you'd like**
A clear and concise description of the content you'd like to see in the new documentation page.

**Describe related documentation pages or resources you've considered**
A clear and concise description of any related documentation pages, resources, or other sources of information you've considered.

**Additional context**
Add any other context, examples, or screenshots about the documentation request here.

**Comment by timothymcmackin** [comment]
@Georgezhang714 Can you provide any info on what you're asking for? It looks like you've posted the new page request template without filling in any of the prompts.
