### ISSUE TITLE
[BUG] Taquito Wallet Setup Code leads to Beacon "Awaiting confirmation" popup not closing after successfull confirmation

### ISSUE THREAD

**Issue by mschmidm** [trilitech/tezos-developer-docs#165]
**Describe the bug**

The code sample provided at the [Taquito Wallet Setup](https://docs.tezos.com/app-development/taquito/#wallet-setup) is not working as intended. I tried it on NextJs and VueJs and got the same bug: the popup Beacon "Awaiting confirmation" does not close after the user successfully connects his wallet.

**To Reproduce**
1. Complete the first steps of the docs (General setup, Wallet setup)
2. Connect the wallet
3. The console logs a successfully connection (which is correct) but the Beacon popup does not close and waits for confirmation forever.

**Expected behavior**
The docs should have a working example.

**Potential bug cause**
I noticed that removing the EventHandler resolves the bug.
```
import { TezosToolkit } from '@taquito/taquito'
import { BeaconWallet } from '@taquito/beacon-wallet'
import { NetworkType } from '@airgap/beacon-types';

const Tezos = new TezosToolkit('https://ghostnet.ecadinfra.com')
const options = {
  name: 'MyAwesomeDapp',
  iconUrl: 'https://tezostaquito.io/img/favicon.svg',
  preferredNetwork: NetworkType.GHOSTNET,
//  eventHandlers: {
//    PERMISSION_REQUEST_SUCCESS: {
//      handler: async (data) => {
//        console.log('permission data:', data)
//      },
//    },
//  },
}
const wallet = new BeaconWallet(options)
await wallet.requestPermissions({
  network: { type: NetworkType.GHOSTNET },
})
Tezos.setWalletProvider(wallet)
```
Thank you for working on the Docs! :)

**Comment by timothymcmackin** [comment]
Thanks for the correction. I have reproduced the problem and added the fix to https://github.com/trilitech/tezos-developer-docs/pull/167.

**Comment by timothymcmackin** [comment]
Fixed by https://github.com/trilitech/tezos-developer-docs/pull/167.
