### ISSUE TITLE
[BUG] Taquito Wallet Setup: DAppClientOptions.preferredNetwork is deprecated

### ISSUE THREAD

**Issue by mschmidm** [trilitech/tezos-developer-docs#166]
**Describe the bug**
In the [Taquito Wallet Setup](https://docs.tezos.com/app-development/taquito/#wallet-setup) the DAppClientOptions are configured with the preferredNetwork attribute, which is deprecated. Instead, "network" should be used (Source: [DAppClientOptions.ts#L82-L92](https://github.com/airgap-it/beacon-sdk/blob/9bd66991f2424a9bdfe458d264ee08ba8b8086ab/packages/beacon-dapp/src/dapp-client/DAppClientOptions.ts#L82-L92))

Thank you! :)

**Comment by timothymcmackin** [comment]
Thanks for identifying this! I've put a fix in a PR.

**Comment by timothymcmackin** [comment]
Fixed by https://github.com/trilitech/tezos-developer-docs/pull/167.
