### ISSUE TITLE
https://metamask.tezos.com/

### ISSUE THREAD

**Issue by mattgale33** [trilitech/tezos-developer-docs#433]
https://github.com/user-attachments/assets/2f9bf479-13ad-4356-86d9-099665243c94

Hi,

So when trying to use the new stake.tezos.com app i am unable to stake using the metamask plug in. Simply get an error stating Error occured in delegate operation, try again. :The action was aborted by the user.

When i then try to send funds back from https://metamask.tezos.com/ i get an operation error occured message.

I have been in contact with Metamask who have been able to replicate the issue but claim its a Tezos fault and not a metamask issue.

Could this be looked into please?

**Comment by timothymcmackin** [comment]
Hi there! The best place to ask for technical support is the Tezos Discord at https://discord.gg/yXaPy6s5Nr. You can file a ticket in the `#support` channel and someone will be able to help.
